In [1]:
import numpy as np

In [2]:
#Importing dataset
from sklearn.datasets import load_digits   # Importing dataset # sklearn.datasets has some predefined ready-made datasets

In [3]:
digits = load_digits()          # Calling load_digits method # 'Dir' displays directory of files and directories stored on disk

In [4]:
dir(digits)                     # To explore what is contained in 'load_digits'

['DESCR', 'data', 'images', 'target', 'target_names']

In [5]:
# Splitting the whole dataset into Training & Testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3, random_state=39)

In [6]:
# Shape of the Training & Testing sets
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1257, 64)
(1257,)
(540, 64)
(540,)


----

Checking Score with different models

In [7]:
# For Logistic Regression classifier
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(solver='liblinear', multi_class='auto')
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.9574074074074074

In [8]:
# For SVM classifier
from sklearn.svm import SVC
svm = SVC(gamma='auto')
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.4203703703703704

In [9]:
# For RandomForest classifier
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9629629629629629

---

We will use cross_val_score function instead of writing long code

In [10]:
# Importing cross_val_score
from sklearn.model_selection import cross_val_score

In [11]:
# Calling cross_val_score for Logistic Regression performance
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target, cv=5)

array([0.92307692, 0.88121547, 0.94986072, 0.95798319, 0.89295775])

In [12]:
# Calling cross_val_score for SVM performance
cross_val_score(SVC(gamma='auto'), digits.data, digits.target, cv=5)

array([0.43406593, 0.40883978, 0.41504178, 0.48739496, 0.49859155])

In [13]:
# Calling cross_val_score for Random Forest Classifier
cross_val_score(RandomForestClassifier(n_estimators=100), digits.data, digits.target, cv=5)

array([0.93406593, 0.90607735, 0.9637883 , 0.96078431, 0.92394366])